name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
        run: pnpm run chain & pnpm run deploy

      - name: Run nextjs lint
        run: pnpm run next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: pnpm run next:check-types

      - name: Run hardhat lint
        run: pnpm run hardhat:lint --max-warnings=0
